### PR TITLE
Saved Flights Activity.

### LINKED ISSUE #5: Cancel Flight Activity
- Verify user's information is correct.
- Verify that  the user has any flights
- Verify that the flight is able to be canceled
- Update the DB.

### LINKED ISSUE #9: Saved Flights Activity
Allows users to view all saved flight tickets. Dependent on #18 
- Add filters, so user can filter flights
- Display individual ticket information on click
- Look for specific design on Figma

### PR DESCRIPTION
**Pull request by sagarprasad63574**
I worked on the Saved Flights Activity. I'm not sure if it will work properly.  I also used a recycler view, its on flightListAdapter.java. I adjusted some design layouts for create, home, landing, and login activities.

### CODE REVIEW

**Comment by Niko-113** [comment]
So I tried adding some flights to a user manually to test it out, and after making a quick fix it appears to be working properly. :+1: 

That being said, I think the design of the layout should be finished before pushing it to main.

**Comment by BorisMarin8004** [comment]
We already have this file: app/src/main/java/com/example/flightticket/FlightListAdapter.java  in utils
Here: https://github.com/BorisMarin8004/FlightTicket/tree/main/app/src/main/java/com/example/flightticket/utils

**Comment by sagarprasad63574** [comment]
> We already have this file: app/src/main/java/com/example/flightticket/FlightListAdapter.java in utils
> Here: https://github.com/BorisMarin8004/FlightTicket/tree/main/app/src/main/java/com/example/flightticket/utils

I tried to using the flightlistadapter but it didn't work properly. So I just made a different adapter.

**Comment by sagarprasad63574** [comment]
> So I tried adding some flights to a user manually to test it out, and after making a quick fix it appears to be working properly. 👍
> 
> That being said, I think the design of the layout should be finished before pushing it to main.

Great Thanks

**Comment by BorisMarin8004** [comment]
> > We already have this file: app/src/main/java/com/example/flightticket/FlightListAdapter.java in utils
> > Here: https://github.com/BorisMarin8004/FlightTicket/tree/main/app/src/main/java/com/example/flightticket/utils
> 
> I tried to using the flightlistadapter but it didn't work properly. So I just made a different adapter.

Could you tell more about it, what did not work?

**Review by BorisMarin8004 — APPROVED** [review]

**Review by Niko-113 — APPROVED** [review]

**Review by larafonse — APPROVED** [review]
LGTM

**Pull request merged**
